# Generated by Django 3.1.5 on 2021-01-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('descripccion', models.CharField(max_length=35)),
                ('num_jugadores', models.IntegerField()),
            ],
        ),
    ]
