# Generated by Django 3.1.5 on 2021-05-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polideportivo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pista',
            name='imagen',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
