# Generated by Django 3.1.5 on 2021-05-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polideportivo', '0002_pista_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pista',
            name='descripcion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pista',
            name='imagen',
            field=models.ImageField(upload_to='polideportivo/images/'),
        ),
    ]
