# Generated by Django 3.1.5 on 2021-05-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polideportivo', '0003_auto_20210517_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pista',
            name='imagen',
            field=models.ImageField(upload_to='polideportivo/images'),
        ),
    ]
