# Generated by Django 3.1.5 on 2021-05-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polideportivo', '0004_auto_20210518_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='pista',
            name='precio',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
