# Generated by Django 3.1.5 on 2021-05-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polideportivo', '0005_pista_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='apellido_cliente',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='dni_cliente',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='nombre_cliente',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
