# Generated by Django 3.1.5 on 2021-06-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polideportivo', '0007_reserva_email_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='reserva_horario',
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='precio_final',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
